version: '3.8'
services:
    reverb-server:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: reverb_server
        restart: unless-stopped
        ports:
            - "3331:80"
            - "3332:8080"
        volumes:
            - '.:/var/www'
#        environment:
#            - APP_ENV=production
        networks:
            - reverb-network
    redis:
        image: 'redis:latest'
        restart: unless-stopped
        networks:
            - reverb-network
networks:
    reverb-network:
        driver: bridge
volumes:
    sail-redis:
        driver: local
